blank_issues_enabled: true
contact_links:
  - name: 📚 Help
    url: https://github.com/hawkeye116477/playnite-gog-oss-plugin/wiki
    about: Read it before asking or reporting anything.
  - name: 🗨️ Forum
    url: https://github.com/hawkeye116477/playnite-gog-oss-plugin/discussions
    about: Please ask and answer questions here.
